version: '3.8'

services:
  db:
    image: postgres:latest
    env_file: ./settings/prod.env
    environment:
      POSTGRES_USER: client_db
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_trade
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  fastapi:
    build: .
    env_file: ./settings/prod.env
    ports:
      - "8000:8000"
    depends_on:
      - db

  parser:
    build: .
    env_file: ./settings/prod.env
    ports:
      - "8001:8001"
    depends_on:
      - db

volumes:
  postgres_data:
