version: '3.8'

services:
  db:
    image: postgres:13
    env_file: ./settings/.prod  
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: usersdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  backend:
    build: .
    env_file: ./settings/.prod
    ports:
      - "8000:8000"
    depends_on:
      - db

  parser_kucoin:
    build: backend/parser_kucoin/
    env_file: ./settings/.prod
    ports:
      - "8001:8001"
    depends_on:
      - db

volumes:
  postgres_data:
