"""empty message

Revision ID: 300a738ce866
Revises: 4f342aefb734
Create Date: 2025-06-12 06:08:06.239914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '300a738ce866'
down_revision: Union[str, None] = '4f342aefb734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column('coins', sa.Column('max_price_now', sa.Float(), nullable=True))
    op.execute("UPDATE coins SET max_price_now = 1.0")
    op.add_column('coins', sa.Column('min_price_now', sa.Float(), nullable=True))
    op.execute("UPDATE coins SET min_price_now = 1.0")
    op.add_column('coins', sa.Column('open_price_now', sa.Float(), nullable=True))
    op.execute("UPDATE coins SET open_price_now = 1.0")
    op.add_column('coins', sa.Column('volume_now', sa.Float(), nullable=True))
    op.execute("UPDATE coins SET volume_now = 1.0")



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coins', 'volume_now')
    op.drop_column('coins', 'open_price_now')
    op.drop_column('coins', 'min_price_now')
    op.drop_column('coins', 'max_price_now')
    # ### end Alembic commands ###
