"""empty message

Revision ID: 5568ab957685
Revises: 0a71cbcb8585
Create Date: 2025-06-13 16:25:54.307660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5568ab957685'
down_revision: Union[str, None] = '0a71cbcb8585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_features', sa.Column('feature_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_agent_features_feature_id_features'), 'agent_features', 'features', ['feature_id'], ['id'])
    op.drop_column('agent_features', 'feature')
    op.drop_column('agent_features', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_features', sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('agent_features', sa.Column('feature', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_agent_features_feature_id_features'), 'agent_features', type_='foreignkey')
    op.drop_column('agent_features', 'feature_id')
    # ### end Alembic commands ###
