"""empty message

Revision ID: 1e035e042d74
Revises: 21a9b8ed7077
Create Date: 2025-06-11 15:09:41.171051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e035e042d74'
down_revision: Union[str, None] = '21a9b8ed7077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coins', 'news_score_global',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('train_coins', sa.Column('train_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('fk_train_coins_strategy_id_strategys'), 'train_coins', type_='foreignkey')
    op.create_foreign_key(op.f('fk_train_coins_train_id_agent_trains'), 'train_coins', 'agent_trains', ['train_id'], ['id'])
    op.drop_column('train_coins', 'strategy_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('train_coins', sa.Column('strategy_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_train_coins_train_id_agent_trains'), 'train_coins', type_='foreignkey')
    op.create_foreign_key(op.f('fk_train_coins_strategy_id_strategys'), 'train_coins', 'strategys', ['strategy_id'], ['id'])
    op.drop_column('train_coins', 'train_id')
    op.alter_column('coins', 'news_score_global',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
