"""empty message

Revision ID: 7fe6690241bd
Revises: 749e56935806
Create Date: 2025-06-05 02:15:54.607040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fe6690241bd'
down_revision: Union[str, None] = '749e56935806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coins', sa.Column('parsed', sa.Boolean(), nullable=True))
    op.execute("UPDATE coins SET parsed = true")
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('coins', 'parsed')
    # ### end Alembic commands ###
