"""empty message

Revision ID: b9bd92103cc5
Revises: 84f5166ccf67
Create Date: 2025-06-10 17:07:35.097393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9bd92103cc5'
down_revision: Union[str, None] = '84f5166ccf67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'a_conficent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.add_column('transactions', sa.Column('amount', sa.Float(), nullable=False))
    op.add_column('transactions', sa.Column('price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'price')
    op.drop_column('transactions', 'amount')
    op.alter_column('agents', 'a_conficent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###
