"""empty message

Revision ID: 84f5166ccf67
Revises: 7fe6690241bd
Create Date: 2025-06-09 22:10:18.398261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84f5166ccf67'
down_revision: Union[str, None] = '7fe6690241bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column('agents', sa.Column('a_conficent', sa.Float(), nullable=True))
    op.execute("UPDATE agents SET a_conficent = 1.0")
    op.alter_column('coins', 'parsed',
               existing_type=sa.BOOLEAN(),
               nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coins', 'parsed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('agents', 'a_conficent')
    # ### end Alembic commands ###
