"""empty message

Revision ID: 853d8f04b62b
Revises: f8e9304c8dff
Create Date: 2025-06-14 13:26:26.085154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '853d8f04b62b'
down_revision: Union[str, None] = 'f8e9304c8dff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_trains', sa.Column('loss_now', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_trains', 'loss_now')
    # ### end Alembic commands ###
