"""empty message

Revision ID: b99a7b65d61a
Revises: 4fd20e629d65
Create Date: 2025-06-11 17:38:45.322473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b99a7b65d61a'
down_revision: Union[str, None] = '4fd20e629d65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategys', sa.Column('name', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategys', 'name')
    # ### end Alembic commands ###
