"""empty message

Revision ID: de0c430d8a7c
Revises: 9e45071d3199
Create Date: 2025-06-13 23:16:36.019480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de0c430d8a7c'
down_revision: Union[str, None] = '9e45071d3199'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_feature_values', sa.Column('feature_name', sa.String(length=50), nullable=False))
    op.alter_column('agent_feature_values', 'value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_feature_values', 'value',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_column('agent_feature_values', 'feature_name')
    # ### end Alembic commands ###
