"""empty message

Revision ID: 8f86faec7c54
Revises: f0d1fe578b59
Create Date: 2025-06-18 22:10:20.505096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f86faec7c54'
down_revision: Union[str, None] = 'f0d1fe578b59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_urls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('a_pup', sa.Float(), nullable=False),
    sa.Column('parsed', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news_urls')),
    sa.UniqueConstraint('url', name=op.f('uq_news_urls_url'))
    )
    op.create_table('telegram_channels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('chat_id', sa.String(length=50), nullable=False),
    sa.Column('parsed', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_channels')),
    sa.UniqueConstraint('chat_id', name=op.f('uq_telegram_channels_chat_id')),
    sa.UniqueConstraint('name', name=op.f('uq_telegram_channels_name'))
    )
    op.alter_column('coins', 'news_score_global',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.add_column('newss', sa.Column('id_url', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('newss', 'id_url')
    op.alter_column('coins', 'news_score_global',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_table('telegram_channels')
    op.drop_table('news_urls')
    # ### end Alembic commands ###
