"""empty message

Revision ID: 4d0f060fa769
Revises: 635c1422bb8d
Create Date: 2025-06-10 17:33:42.525634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d0f060fa769'
down_revision: Union[str, None] = '635c1422bb8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistic_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_model', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('loss', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('precision', sa.Float(), nullable=False),
    sa.Column('recall', sa.Float(), nullable=False),
    sa.Column('f1score', sa.Float(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_model'], ['m_l__models.id'], name=op.f('fk_statistic_models_id_model_m_l__models'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statistic_models'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statistic_models')
    # ### end Alembic commands ###
