"""empty message

Revision ID: f0d1fe578b59
Revises: 853d8f04b62b
Create Date: 2025-06-15 14:43:16.892976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0d1fe578b59'
down_revision: Union[str, None] = '853d8f04b62b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coins', sa.Column('price_change_percentage_24h', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coins', 'price_change_percentage_24h')
    # ### end Alembic commands ###
