"""empty message

Revision ID: 4f342aefb734
Revises: b99a7b65d61a
Create Date: 2025-06-12 01:15:43.173017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f342aefb734'
down_revision: Union[str, None] = 'b99a7b65d61a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.alter_column('data_timeseriess', 'datetime',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.DateTime(),
               postgresql_using='datetime::timestamp without time zone')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_timeseriess', 'datetime',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
