"""empty message

Revision ID: c7b217b61961
Revises: 1193bb0bc97e
Create Date: 2025-06-14 04:13:12.494772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7b217b61961'
down_revision: Union[str, None] = '1193bb0bc97e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column('agents', sa.Column('status', sa.String(length=20), nullable=True))
    op.execute("UPDATE agents SET status = 'open'")



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'status')
    # ### end Alembic commands ###
