"""empty message

Revision ID: 635c1422bb8d
Revises: b9bd92103cc5
Create Date: 2025-06-10 17:32:01.384225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '635c1422bb8d'
down_revision: Union[str, None] = 'b9bd92103cc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_l__models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('path_model', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_m_l__models')),
    sa.UniqueConstraint('path_model', name=op.f('uq_m_l__models_path_model'))
    )
    op.create_table('statistic_agents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_agnet', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('loss', sa.Float(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_agnet'], ['agents.id'], name=op.f('fk_statistic_agents_id_agnet_agents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statistic_agents'))
    )
    op.drop_table('news_models')
    op.drop_table('mmms')
    op.drop_table('risk_models')
    op.add_column('agents', sa.Column('type', sa.String(length=50), nullable=False))
    op.alter_column('agents', 'version',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_agents_version'), 'agents', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_agents_version'), 'agents', ['version'], postgresql_nulls_not_distinct=False)
    op.alter_column('agents', 'version',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('agents', 'type')
    op.create_table('risk_models',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('path_model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_models')),
    sa.UniqueConstraint('path_model', name=op.f('uq_risk_models_path_model'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('version', name=op.f('uq_risk_models_version'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('mmms',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('path_model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mmms')),
    sa.UniqueConstraint('path_model', name=op.f('uq_mmms_path_model'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('version', name=op.f('uq_mmms_version'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('news_models',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('path_model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news_models')),
    sa.UniqueConstraint('path_model', name=op.f('uq_news_models_path_model'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('version', name=op.f('uq_news_models_version'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('statistic_agents')
    op.drop_table('m_l__models')
    # ### end Alembic commands ###
